'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DocReceivingReport

    '''<summary>
    '''dlMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlMonth As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbYear As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbDeliveredBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDeliveredBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btPreview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbPreparedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPreparedBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbPreparedByDesignation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPreparedByDesignation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbReviewedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbReviewedBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbReviewedByDesignation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbReviewedByDesignation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbSubmittedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSubmittedBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbSubmittedByDesignation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSubmittedByDesignation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lmsg As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ReportViewer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportViewer1 As Global.Microsoft.Reporting.WebForms.ReportViewer

    '''<summary>
    '''ds_reportdata control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_reportdata As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ds_reportdata2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_reportdata2 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ds_reportdatasummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_reportdatasummary As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ds_reportdatagraphsummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_reportdatagraphsummary As Global.System.Web.UI.WebControls.SqlDataSource
End Class
