'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Import

    '''<summary>
    '''lRecordCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lRecordCount As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''imgAddDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddDoc As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ucUploadFiles1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucUploadFiles1 As Global.dms.ucUploadFiles

    '''<summary>
    '''ucViewFiles1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucViewFiles1 As Global.dms.ucViewFiles

    '''<summary>
    '''imprt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imprt As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cbFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbFileName As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''uploadFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uploadFileName As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''lImportFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lImportFileName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlDocType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDocType As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbDocType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDocType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''cbDocType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDocType As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lSelectDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lSelectDoc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dlDocType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlDocType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lDocTypeColNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lDocTypeColNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbDocTypeColNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDocTypeColNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lOfficeColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lOfficeColumn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lOfficeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lOfficeCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbOfficeColumnNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbOfficeColumnNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dlOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlOffice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbFileNameColNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFileNameColNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rbDocLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDocLoc As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''tbLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLocation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btUploadFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btUploadFiles As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''imgViewFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgViewFiles As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''dlStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btUpload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btUploadFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btUploadFileName As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''step5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents step5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btImport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btImport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMsg As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rptDocIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptDocIndex As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptUpload As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As dms.Site
        Get
            Return CType(MyBase.Master, dms.Site)
        End Get
    End Property
End Class
