'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucDashboardCount

    '''<summary>
    '''pDB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pDB As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hfStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfStartDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfEndDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfPersonnelInCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPersonnelInCharge As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSubject As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfRefNo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfDueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDueDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfStatus As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfOfcCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfOfcCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfAction As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ltdr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltdr As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''imgShowAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgShowAction As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pnlAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAction As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ladr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ladr As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lnadr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnadr As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lpd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lpd As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lbopd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbopd As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lopd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lopd As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lbnpd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbnpd As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnpd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnpd As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lapd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lapd As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lcd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcd As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblcd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcd As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''llcd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents llcd As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lbqcd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbqcd As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lqcd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lqcd As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lacd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lacd As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''hfReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfReset As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pChartDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pChartDays As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''imgDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDays As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''trChartDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trChartDays As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tblChartDaysPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblChartDaysPage As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''hfCurrentChartDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCurrentChartDays As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''imgChartDaysPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgChartDaysPrevious As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lTotalChartDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTotalChartDays As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgChartDaysNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgChartDaysNext As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ChartDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChartDays As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''imgPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPending As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''trChartPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trChartPending As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''pChartPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pChartPending As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''tblChartPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblChartPending As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''hfChartPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfChartPending As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''imgChartPendingPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgChartPendingPrevious As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lChartPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lChartPending As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgChartPendingNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgChartPendingNext As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ChartPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChartPending As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''gDistribution control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gDistribution As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''imgDistribution control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDistribution As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pChartDistribution control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pChartDistribution As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ChartDistribution control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChartDistribution As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''gTotalAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gTotalAmount As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''imgBk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBk As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pnlTotalAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTotalAmount As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rptTotalAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptTotalAmount As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''gAged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gAged As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''imgAged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAged As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pnlAged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAged As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rptAged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAged As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''gQuick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gQuick As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''imgQuick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgQuick As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pnlQuick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlQuick As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rptQuick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptQuick As Global.System.Web.UI.WebControls.Repeater
End Class
