'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucReply

    '''<summary>
    '''pReply1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pReply1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pReply control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pReply As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tbAdditionalDoc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAdditionalDoc1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbAdditionalDoc5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAdditionalDoc5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbAdditionalDoc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAdditionalDoc2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbAdditionalDoc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAdditionalDoc3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbAdditionalDoc4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAdditionalDoc4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pMsgx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pMsgx As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgCloseAck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCloseAck As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pSaveInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pSaveInfo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hnextid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hnextid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hprevid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hprevid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hcurrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hcurrid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlRepDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRepDoc As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLogo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lAddress As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tbRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbRefNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbReplyDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbReplyDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cl0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cl0 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''ldocid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ldocid As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Literal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lPby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lPby As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lPdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lPdate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lreplyid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lreplyid As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tbClientAgency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbClientAgency As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbThisPertains control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbThisPertains As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lThisPertains control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lThisPertains As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tbSubmittedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSubmittedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cl1 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''tbWhichWas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbWhichWas As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lWhichWas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lWhichWas As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tbReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbReceivedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cl2 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''imgcbxAdditional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgcbxAdditional As Global.dms.ucCheckBox

    '''<summary>
    '''tbInOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbInOrder As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lInOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lInOrder As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''EditorAddDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditorAddDoc As Global.AjaxControlToolkit.HTMLEditor.Editor

    '''<summary>
    '''pContentAddDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pContentAddDoc As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tbPleaseIndicate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPleaseIndicate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lPleaseIndicate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lPleaseIndicate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tbSubmitDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSubmitDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender1 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''imgcbxReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgcbxReturn As Global.dms.ucCheckBox

    '''<summary>
    '''imgcbxComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgcbxComplete As Global.dms.ucCheckBox

    '''<summary>
    '''imgcbxPartial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgcbxPartial As Global.dms.ucCheckBox

    '''<summary>
    '''tbNoPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNoPages As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbBasedOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBasedOn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lBasedOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lBasedOn As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''imgcbxDeficiency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgcbxDeficiency As Global.dms.ucCheckBox

    '''<summary>
    '''tbSpecificDoc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSpecificDoc1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbSpecificDoc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSpecificDoc2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbSpecificDoc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSpecificDoc3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EditorSpecific control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditorSpecific As Global.AjaxControlToolkit.HTMLEditor.Editor

    '''<summary>
    '''pContentSpecific control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pContentSpecific As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''imgcbxWithdrawal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgcbxWithdrawal As Global.dms.ucCheckBox

    '''<summary>
    '''tbWReferenceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbWReferenceNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EditorWithdrawal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditorWithdrawal As Global.AjaxControlToolkit.HTMLEditor.Editor

    '''<summary>
    '''pContentWithdrawal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pContentWithdrawal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tbBureauHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBureauHead As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btPrint As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btPost As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btEditReply control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btEditReply As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btSaveReply control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSaveReply As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btEmailReply control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btEmailReply As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lmsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLeft As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgRight As Global.System.Web.UI.WebControls.ImageButton
End Class
