'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserControlDocRouting

    '''<summary>
    '''pnl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hfSeqNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSeqNo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfRefNo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfMaxSeqNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfMaxSeqNo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTitle As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfMaxSeqNoToCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfMaxSeqNoToCancel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfCCSeqNoToCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCCSeqNoToCancel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfDocType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDocType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfDocid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDocid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfOfficeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfOfficeCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfStatusId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfStatusId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgAddApprover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddApprover As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgAddCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddCC As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgSaveDueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSaveDueDate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pConfirm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ltext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltext As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btContinue As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btSaveCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSaveCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pSearchCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pSearchCriteria As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pTitle As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''imgSendApprover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSendApprover As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgQuickApprover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgQuickApprover As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHelp As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgClose As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pnlRtInstruction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRtInstruction As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''RouteInstruction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RouteInstruction As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lOutS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lOutS As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lApproverSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lApproverSelected As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptList As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pSearchCriteria2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pSearchCriteria2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''dlSearchType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlSearchType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtBx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBx As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dlGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlGroups As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''imgSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSearch As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lSearchMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lSearchMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptSub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSub As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pCopyFurnish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pCopyFurnish As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgSendCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSendCC As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgCloseCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCloseCC As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''rptCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCopy As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCC As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''dlCCSearchType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlCCSearchType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCCBx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCCBx As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dlCCGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlCCGroups As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''imgCCSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCCSearch As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lCCSearchMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lCCSearchMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptCCSub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCCSub As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rpt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpt As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCC As Global.System.Web.UI.WebControls.Repeater
End Class
