'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserControlImgViewer

    '''<summary>
    '''PanelViewer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelViewer1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PanelViewer2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelViewer2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlImg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlImg As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lZoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lZoom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dlZoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlZoom As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hfHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfHeight As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfWidth As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''imgSrc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSrc As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgClose As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pnlImageDisp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlImageDisp As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgHandler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHandler As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''dse2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dse2 As Global.AjaxControlToolkit.DropShadowExtender
End Class
