'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserControlIssuanceFolder

    '''<summary>
    '''hfFolderId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFolderId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfFolderDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFolderDesc As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFolder As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rptFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptFolder As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''FolderAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FolderAdd As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFolder As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lcheckmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcheckmsg As Global.System.Web.UI.WebControls.Label
End Class
