'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class view

    '''<summary>
    '''uReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uReceipt As Global.dms.ucReceipt

    '''<summary>
    '''uReceiptRoute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uReceiptRoute As Global.dms.ucReceiptRoute

    '''<summary>
    '''uBlankRoute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uBlankRoute As Global.dms.ucReceiptRouteBlank

    '''<summary>
    '''uBlankRoute2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uBlankRoute2 As Global.dms.ucReceiptRouteBlank2

    '''<summary>
    '''uReply control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uReply As Global.dms.ucReply

    '''<summary>
    '''ucAddDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucAddDoc As Global.dms.ucButton

    '''<summary>
    '''ucCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucCon As Global.dms.ucConfirm

    '''<summary>
    '''ucCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucCancel As Global.dms.ucConfirm

    '''<summary>
    '''ucResetRet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucResetRet As Global.dms.ucConfirm

    '''<summary>
    '''ucRemoveRet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucRemoveRet As Global.dms.ucConfirm

    '''<summary>
    '''ucCreateSubTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucCreateSubTask As Global.dms.ucConfirm

    '''<summary>
    '''pDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pDownload As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btDownload As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDownload As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pEdit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSave As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbEdit As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pDelDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pDelDoc As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgDelDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDelDoc As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbDelDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDelDoc As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pArchiveTrue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pArchiveTrue As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgArchiveTrue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgArchiveTrue As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbArchiveTrue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbArchiveTrue As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pReceipt As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgReceipt As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbReceipt As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pBlankReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pBlankReceipt As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgBReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBReceipt As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbBReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbBReceipt As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pRouteSlip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pRouteSlip As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgRouteSlip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgRouteSlip As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbRouteSlip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRouteSlip As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pBRouteSlip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pBRouteSlip As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgBRouteSlip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBRouteSlip As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbBRouteSlip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbBRouteSlip As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pBRouteSlip2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pBRouteSlip2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgBRouteSlip2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBRouteSlip2 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbBRouteSlip2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbBRouteSlip2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pReply control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pReply As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgReply control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgReply As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbReply control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbReply As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pCheckOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pCheckOut As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgCheckout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCheckout As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbCheckOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCheckOut As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pCheckIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pCheckIn As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgCheckIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCheckIn As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbCheckin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCheckin As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pShare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pShare As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgEmail As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbShare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbShare As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ucb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucb As Global.dms.UserControlBookMark

    '''<summary>
    '''lrefno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lrefno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lCreatedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lCreatedDate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''upnlBkMark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlBkMark As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''imgBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBack As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgBook control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBook As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgBookM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBookM As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''hlNewTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlNewTab As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlOpen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlOpen As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lbUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUpload As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ImageButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''hlNewTab2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlNewTab2 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''imgPDFPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPDFPrint As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lFileSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lFileSize As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pDocInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pDocInfo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlDocInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDocInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tbTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTitle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lFileName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lVersionShow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lVersionShow As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lVersion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lDocName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lDocName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''dlDocType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlDocType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lDateUploaded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lDateUploaded As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''dlClassification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlClassification As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lToClassification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lToClassification As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lClassification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lClassification As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lClassificationCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lClassificationCode As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lAuthor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lAuthor As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lAuthorID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lAuthorID As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lsendername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsendername As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lsender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsender As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tbSenderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSenderName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lIsCheckOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lIsCheckOut As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''dlRequestType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlRequestType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lToNewRequestType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lToNewRequestType As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lRequestDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lRequestDescription As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lRequestType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lRequestType As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lCheckoutBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lCheckoutBy As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''dlOfficeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlOfficeCode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lToNewOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lToNewOffice As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lsOfficeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsOfficeName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lsOfficeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsOfficeCode As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lPrinted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lPrinted As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lstatusid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstatusid As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''dlStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lToNewStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lToNewStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgEmailPointPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgEmailPointPerson As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''tbDueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDueDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender2 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''lOrigDueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lOrigDueLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lOrigDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lOrigDue As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''pStatusUpd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pStatusUpd As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dlFinalStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlFinalStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lDocStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lDocStat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lCdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lCdate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''dlManner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlManner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lTOManner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTOManner As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lManner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lManner As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lMannerId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lMannerId As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''trCopies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCopies As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tbNoCopies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNoCopies As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lNoCopies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lNoCopies As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''pReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pReturn As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlRet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRet As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lLabelReturnCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lLabelReturnCard As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tbReturnCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbReturnCard As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lReturnCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lReturnCard As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tbNoPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNoPages As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lNoPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lNoPages As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tbReceivedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbReceivedBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lReceivedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lReceivedBy As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lconftext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lconftext As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lConf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lConf As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''upConf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upConf As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cbConf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbConf As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tbReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbReceivedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender1 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''lReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lReceivedDate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tbReceivedTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbReceivedTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MeExt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MeExt As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''lReceivedTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lReceivedTime As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lcheckmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcheckmsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''upMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upMenu As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pMUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pMUpdate As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btSaveUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSaveUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btCancelUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btCancelUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pMAddTag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pMAddTag As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgUpdate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbAddTag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAddTag As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTab As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TdHistory1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdHistory1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdHistory2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdHistory2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lbHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbHistory As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lHistory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TdHistory3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdHistory3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdView1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdView2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lbView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbView As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lView As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TdView3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdView3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdRouting1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdRouting1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdRouting2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdRouting2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lbRouting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRouting As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lRouting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lRouting As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TdRouting3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdRouting3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdIndex1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdIndex1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdIndex2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdIndex2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lbIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbIndex As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lIndex As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TdIndex3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdIndex3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdLinks1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdLinks1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdLinks2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdLinks2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''pnlLinkCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLinkCount As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lbLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbLinks As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lLinks As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lLinksCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lLinksCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TdLinks3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdLinks3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdNotes1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdNotes1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdNotes2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdNotes2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''pnlNoteCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNoteCount As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lbNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbNotes As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lNotes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lNoteCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lNoteCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TdNotes3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdNotes3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdTags1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdTags1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdTags2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdTags2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lbTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTags As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lTags As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TdTags3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdTags3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdAttach1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdAttach1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdAttach2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdAttach2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''pnlAttachCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAttachCount As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lbAttach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAttach As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lAttach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lAttach As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lAttachCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lAttachCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TdAttach3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdAttach3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdRoutingHistory1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdRoutingHistory1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdRoutingHistory2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdRoutingHistory2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lbRouteHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRouteHistory As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lRouteHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lRouteHistory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TdRoutingHistory3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdRoutingHistory3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdSubTask1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdSubTask1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TdSubTask2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdSubTask2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''pnlSubTaskCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSubTaskCount As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lbSubTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSubTask As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lSubTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lSubTask As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lSubTaskCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lSubTaskCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TdSubTask3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TdSubTask3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Td22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Td22 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''imgHideShow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHideShow As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pDocView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pDocView As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlVersion As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ucVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucVersion As Global.dms.UserControlVersion

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''docvw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents docvw As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pDocRouting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pDocRouting As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlDocRouting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDocRouting As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ucDocRouting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucDocRouting As Global.dms.UserControlDocRouting

    '''<summary>
    '''pDocHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pDocHistory As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlDocHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDocHistory As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''hfCurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCurrent As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfTotalRows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTotalRows As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ucPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucPager As Global.dms.UserControlPager

    '''<summary>
    '''ucDocHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucDocHistory As Global.dms.UserControlDashBoard

    '''<summary>
    '''pDocIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pDocIndex As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlDocIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDocIndex As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlIndex As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ucDocIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucDocIndex As Global.dms.UserControlDocumentIndex

    '''<summary>
    '''btSaveIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSaveIndex As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pDocLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pDocLinks As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlDocLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDocLinks As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UserDocLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserDocLinks As Global.dms.UserControlDocLink

    '''<summary>
    '''pDocNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pDocNotes As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlDocNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDocNotes As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UserDocNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserDocNotes As Global.dms.UserControlDocNotes

    '''<summary>
    '''pDocTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pDocTags As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlDocTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDocTags As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UControlTAG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UControlTAG As Global.dms.UserControlTag

    '''<summary>
    '''pAttachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pAttachment As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlAttachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAttachment As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''uControlAttach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uControlAttach As Global.dms.UserControlAttachment

    '''<summary>
    '''pnAddAttachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnAddAttachment As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgAttachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAttachment As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbAttachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAttachment As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pRoutingHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pRoutingHistory As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlRoutingHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRoutingHistory As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''hfRoutingHistoryCurrentRows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfRoutingHistoryCurrentRows As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfRoutingHistoryTotalRows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfRoutingHistoryTotalRows As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ucPagerRoutingHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucPagerRoutingHistory As Global.dms.UserControlPager

    '''<summary>
    '''uTrackStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uTrackStatus As Global.dms.ucTrackStatus

    '''<summary>
    '''pSubTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pSubTask As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlSubTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSubTask As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSelect As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''uSTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uSTask As Global.dms.ucSubTask

    '''<summary>
    '''pnlAddSubTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAddSubTask As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgAddSubTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddSubTask As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbAddSubTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAddSubTask As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''upEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upEmail As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''uEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uEmail As Global.dms.ucPromptEmail

    '''<summary>
    '''pnlCancelCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCancelCC As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''uPromptCancelCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uPromptCancelCC As Global.dms.ucPrompt

    '''<summary>
    '''pnlCancelRoute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCancelRoute As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''uPromptCancelRoute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uPromptCancelRoute As Global.dms.ucPrompt

    '''<summary>
    '''pnlMergeRoute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMergeRoute As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''uPromptMergeRoute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uPromptMergeRoute As Global.dms.ucPrompt

    '''<summary>
    '''pnlDelSubTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDelSubTask As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''uPromptDelSubTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uPromptDelSubTask As Global.dms.ucPrompt

    '''<summary>
    '''ucShare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucShare As Global.dms.UserControlShare

    '''<summary>
    '''ucUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucUpload As Global.dms.UserControlUpload

    '''<summary>
    '''ucAtt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucAtt As Global.dms.ucAttach

    '''<summary>
    '''ucUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucUp As Global.dms.ucDocUpload

    '''<summary>
    '''pUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pUpload1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pUpload2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pUpload2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pDoc As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lAction As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''imgClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgClose As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pInstuction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pInstuction As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btCheckOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btCheckOut As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btCheckoutCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btCheckoutCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlCheckin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCheckin As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''fileCheckIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fileCheckIn As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''tbComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btUpload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btCancelCheckout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btCancelCheckout As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lcinmessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcinmessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlConfirm As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pConfirm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgSaveCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSaveCancel As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btContinue As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btSaveCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSaveCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dse2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dse2 As Global.AjaxControlToolkit.DropShadowExtender

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As dms.Site
        Get
            Return CType(MyBase.Master, dms.Site)
        End Get
    End Property
End Class
